<?xml version = "1.0" ?>
<?xml-stylesheet type="text/xsl" href="SystemBOM.xsl"?>
<!DOCTYPE GRID [
  <!ELEMENT GRID (BANDS, COLUMNS, ROWS*)>
  <!ATTLIST GRID ExportVersion CDATA #REQUIRED>
  <!ELEMENT BANDS (BAND*)>
  <!ELEMENT BAND EMPTY>
  <!ATTLIST BAND Index CDATA #REQUIRED>
  <!ATTLIST BAND Caption CDATA #IMPLIED>
  <!ELEMENT COLUMNS (COLUMN*)>
  <!ELEMENT COLUMN EMPTY>
  <!ATTLIST COLUMN Name CDATA #REQUIRED>
  <!ATTLIST COLUMN Caption CDATA #IMPLIED>
  <!ATTLIST COLUMN Index CDATA #REQUIRED>
  <!ATTLIST COLUMN BandIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN RowIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN ColIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN Width CDATA #IMPLIED>
  <!ELEMENT GROUP (GROUP*, ROW*)>
  <!ATTLIST GROUP GroupText CDATA #IMPLIED>
  <!ELEMENT ROWS (ROW*)>
  <!ELEMENT ROW EMPTY>
  <!ATTLIST ROW Address1 CDATA #IMPLIED>
  <!ATTLIST ROW Address2 CDATA #IMPLIED>
  <!ATTLIST ROW Address3 CDATA #IMPLIED>
  <!ATTLIST ROW Address4 CDATA #IMPLIED>
  <!ATTLIST ROW Application_BuildNumber CDATA #IMPLIED>
  <!ATTLIST ROW ApprovedBy CDATA #IMPLIED>
  <!ATTLIST ROW Author CDATA #IMPLIED>
  <!ATTLIST ROW Brand CDATA #IMPLIED>
  <!ATTLIST ROW Category CDATA #IMPLIED>
  <!ATTLIST ROW CheckedBy CDATA #IMPLIED>
  <!ATTLIST ROW Class CDATA #IMPLIED>
  <!ATTLIST ROW Code___JEDEC CDATA #IMPLIED>
  <!ATTLIST ROW Comment CDATA #IMPLIED>
  <!ATTLIST ROW CompanyName CDATA #IMPLIED>
  <!ATTLIST ROW Component_Kind CDATA #IMPLIED>
  <!ATTLIST ROW ComponentKind CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink1_Description CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink1Description CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink1URL CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink2_Description CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink2Description CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink2URL CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink3Description CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink3URL CDATA #IMPLIED>
  <!ATTLIST ROW Created_by CDATA #IMPLIED>
  <!ATTLIST ROW Created_Date CDATA #IMPLIED>
  <!ATTLIST ROW CurrentDate CDATA #IMPLIED>
  <!ATTLIST ROW CurrentTime CDATA #IMPLIED>
  <!ATTLIST ROW Datasheet_Link CDATA #IMPLIED>
  <!ATTLIST ROW DatasheetVersion CDATA #IMPLIED>
  <!ATTLIST ROW Date CDATA #IMPLIED>
  <!ATTLIST ROW Description CDATA #IMPLIED>
  <!ATTLIST ROW Designator CDATA #IMPLIED>
  <!ATTLIST ROW Designator_X_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_X_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_Y_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_Y_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW DesignItemId CDATA #IMPLIED>
  <!ATTLIST ROW Direction CDATA #IMPLIED>
  <!ATTLIST ROW Document CDATA #IMPLIED>
  <!ATTLIST ROW DocumentFullPathAndName CDATA #IMPLIED>
  <!ATTLIST ROW DocumentName CDATA #IMPLIED>
  <!ATTLIST ROW DocumentNumber CDATA #IMPLIED>
  <!ATTLIST ROW DrawnBy CDATA #IMPLIED>
  <!ATTLIST ROW Engineer CDATA #IMPLIED>
  <!ATTLIST ROW Footprint CDATA #IMPLIED>
  <!ATTLIST ROW Height CDATA #IMPLIED>
  <!ATTLIST ROW Height_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Height_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW Ibis_Model CDATA #IMPLIED>
  <!ATTLIST ROW ImagePath CDATA #IMPLIED>
  <!ATTLIST ROW Index CDATA #IMPLIED>
  <!ATTLIST ROW Inductance CDATA #IMPLIED>
  <!ATTLIST ROW IR_Max__uA_ CDATA #IMPLIED>
  <!ATTLIST ROW ItemGUID CDATA #IMPLIED>
  <!ATTLIST ROW LatestRevisionDate CDATA #IMPLIED>
  <!ATTLIST ROW LatestRevisionNote CDATA #IMPLIED>
  <!ATTLIST ROW Length CDATA #IMPLIED>
  <!ATTLIST ROW Library_Name CDATA #IMPLIED>
  <!ATTLIST ROW Library_Reference CDATA #IMPLIED>
  <!ATTLIST ROW LibRef CDATA #IMPLIED>
  <!ATTLIST ROW LogicalDesignator CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_1 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_Part_Number CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_Part_Number_1 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_Name CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_Part_Number1 CDATA #IMPLIED>
  <!ATTLIST ROW Maximum_Operating_Temperature CDATA #IMPLIED>
  <!ATTLIST ROW Minimum_Operating_Temperature CDATA #IMPLIED>
  <!ATTLIST ROW Minimum_Order_Quantity CDATA #IMPLIED>
  <!ATTLIST ROW Model_Footprint CDATA #IMPLIED>
  <!ATTLIST ROW Model_Signal_Integrity CDATA #IMPLIED>
  <!ATTLIST ROW Model_Simulation CDATA #IMPLIED>
  <!ATTLIST ROW Models CDATA #IMPLIED>
  <!ATTLIST ROW ModifiedDate CDATA #IMPLIED>
  <!ATTLIST ROW Mounting_Style CDATA #IMPLIED>
  <!ATTLIST ROW Mounting_Technology CDATA #IMPLIED>
  <!ATTLIST ROW Mouser_Part_Number CDATA #IMPLIED>
  <!ATTLIST ROW Mouser_Price_Stock CDATA #IMPLIED>
  <!ATTLIST ROW NoPins CDATA #IMPLIED>
  <!ATTLIST ROW Operating_Supply_Current CDATA #IMPLIED>
  <!ATTLIST ROW Operating_Temperature_Range CDATA #IMPLIED>
  <!ATTLIST ROW Organization CDATA #IMPLIED>
  <!ATTLIST ROW Package___Case CDATA #IMPLIED>
  <!ATTLIST ROW PackageDescription CDATA #IMPLIED>
  <!ATTLIST ROW PackageReference CDATA #IMPLIED>
  <!ATTLIST ROW PackageVersion CDATA #IMPLIED>
  <!ATTLIST ROW Packaging CDATA #IMPLIED>
  <!ATTLIST ROW Packing CDATA #IMPLIED>
  <!ATTLIST ROW partNo CDATA #IMPLIED>
  <!ATTLIST ROW PartNumber CDATA #IMPLIED>
  <!ATTLIST ROW PartType CDATA #IMPLIED>
  <!ATTLIST ROW PCB3D CDATA #IMPLIED>
  <!ATTLIST ROW PhysicalPath CDATA #IMPLIED>
  <!ATTLIST ROW Pins CDATA #IMPLIED>
  <!ATTLIST ROW PPK_Max__W_ CDATA #IMPLIED>
  <!ATTLIST ROW Pricing_1 CDATA #IMPLIED>
  <!ATTLIST ROW Product_Type CDATA #IMPLIED>
  <!ATTLIST ROW Project CDATA #IMPLIED>
  <!ATTLIST ROW ProjectName CDATA #IMPLIED>
  <!ATTLIST ROW Published CDATA #IMPLIED>
  <!ATTLIST ROW Publisher CDATA #IMPLIED>
  <!ATTLIST ROW Quantity CDATA #IMPLIED>
  <!ATTLIST ROW Reeling CDATA #IMPLIED>
  <!ATTLIST ROW Revision CDATA #IMPLIED>
  <!ATTLIST ROW RevisionGUID CDATA #IMPLIED>
  <!ATTLIST ROW RoHS CDATA #IMPLIED>
  <!ATTLIST ROW RoHS___Mouser CDATA #IMPLIED>
  <!ATTLIST ROW RS_Part_Number CDATA #IMPLIED>
  <!ATTLIST ROW RS_Price_Stock CDATA #IMPLIED>
  <!ATTLIST ROW Rule CDATA #IMPLIED>
  <!ATTLIST ROW Series CDATA #IMPLIED>
  <!ATTLIST ROW SheetNumber CDATA #IMPLIED>
  <!ATTLIST ROW SheetTotal CDATA #IMPLIED>
  <!ATTLIST ROW Signal_Integrity CDATA #IMPLIED>
  <!ATTLIST ROW Simulation CDATA #IMPLIED>
  <!ATTLIST ROW size CDATA #IMPLIED>
  <!ATTLIST ROW SourceLibraryName CDATA #IMPLIED>
  <!ATTLIST ROW Standard_Pack_Qty CDATA #IMPLIED>
  <!ATTLIST ROW Stock_1 CDATA #IMPLIED>
  <!ATTLIST ROW Subcategory CDATA #IMPLIED>
  <!ATTLIST ROW Sub_Parts CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Currency_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Order_Qty_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Part_Number_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Stock_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Subtotal_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Unit_Price_1 CDATA #IMPLIED>
  <!ATTLIST ROW Time CDATA #IMPLIED>
  <!ATTLIST ROW Title CDATA #IMPLIED>
  <!ATTLIST ROW typr CDATA #IMPLIED>
  <!ATTLIST ROW UniqueIdName CDATA #IMPLIED>
  <!ATTLIST ROW UniqueIdPath CDATA #IMPLIED>
  <!ATTLIST ROW V_BR__Typ__V_ CDATA #IMPLIED>
  <!ATTLIST ROW Value CDATA #IMPLIED>
  <!ATTLIST ROW Variant CDATA #IMPLIED>
  <!ATTLIST ROW VaultGUID CDATA #IMPLIED>
  <!ATTLIST ROW Width CDATA #IMPLIED>
  <!ATTLIST ROW _ CDATA #IMPLIED>
  <!ATTLIST ROW _ID_ CDATA #IMPLIED>
  <!ATTLIST ROW _PARENTID_ CDATA #IMPLIED>
]>
<GRID ExportVersion="1.0">
  <BANDS>
    <BAND Index="0" Caption=""></BAND>
  </BANDS>
  <COLUMNS>
    <COLUMN Name="Address1" Caption="Address1" Index="0" BandIndex="0" RowIndex="0" ColIndex="0" Width="100"></COLUMN>
    <COLUMN Name="Address2" Caption="Address2" Index="1" BandIndex="0" RowIndex="0" ColIndex="1" Width="100"></COLUMN>
    <COLUMN Name="Address3" Caption="Address3" Index="2" BandIndex="0" RowIndex="0" ColIndex="2" Width="100"></COLUMN>
    <COLUMN Name="Address4" Caption="Address4" Index="3" BandIndex="0" RowIndex="0" ColIndex="3" Width="100"></COLUMN>
    <COLUMN Name="Application_BuildNumber" Caption="Application_BuildNumber" Index="4" BandIndex="0" RowIndex="0" ColIndex="4" Width="100"></COLUMN>
    <COLUMN Name="ApprovedBy" Caption="ApprovedBy" Index="5" BandIndex="0" RowIndex="0" ColIndex="5" Width="100"></COLUMN>
    <COLUMN Name="Author" Caption="Author" Index="6" BandIndex="0" RowIndex="0" ColIndex="6" Width="100"></COLUMN>
    <COLUMN Name="Brand" Caption="Brand" Index="7" BandIndex="0" RowIndex="0" ColIndex="7" Width="100"></COLUMN>
    <COLUMN Name="Category" Caption="Category" Index="8" BandIndex="0" RowIndex="0" ColIndex="8" Width="100"></COLUMN>
    <COLUMN Name="CheckedBy" Caption="CheckedBy" Index="9" BandIndex="0" RowIndex="0" ColIndex="9" Width="100"></COLUMN>
    <COLUMN Name="Class" Caption="Class" Index="10" BandIndex="0" RowIndex="0" ColIndex="10" Width="100"></COLUMN>
    <COLUMN Name="Code___JEDEC" Caption="Code - JEDEC" Index="11" BandIndex="0" RowIndex="0" ColIndex="11" Width="100"></COLUMN>
    <COLUMN Name="Comment" Caption="Comment" Index="12" BandIndex="0" RowIndex="0" ColIndex="12" Width="100"></COLUMN>
    <COLUMN Name="CompanyName" Caption="CompanyName" Index="13" BandIndex="0" RowIndex="0" ColIndex="13" Width="100"></COLUMN>
    <COLUMN Name="Component_Kind" Caption="Component Kind" Index="14" BandIndex="0" RowIndex="0" ColIndex="14" Width="100"></COLUMN>
    <COLUMN Name="ComponentKind" Caption="ComponentKind" Index="15" BandIndex="0" RowIndex="0" ColIndex="15" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink1_Description" Caption="ComponentLink1 Description" Index="16" BandIndex="0" RowIndex="0" ColIndex="16" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink1Description" Caption="ComponentLink1Description" Index="17" BandIndex="0" RowIndex="0" ColIndex="17" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink1URL" Caption="ComponentLink1URL" Index="18" BandIndex="0" RowIndex="0" ColIndex="18" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink2_Description" Caption="ComponentLink2 Description" Index="19" BandIndex="0" RowIndex="0" ColIndex="19" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink2Description" Caption="ComponentLink2Description" Index="20" BandIndex="0" RowIndex="0" ColIndex="20" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink2URL" Caption="ComponentLink2URL" Index="21" BandIndex="0" RowIndex="0" ColIndex="21" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink3Description" Caption="ComponentLink3Description" Index="22" BandIndex="0" RowIndex="0" ColIndex="22" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink3URL" Caption="ComponentLink3URL" Index="23" BandIndex="0" RowIndex="0" ColIndex="23" Width="100"></COLUMN>
    <COLUMN Name="Created_by" Caption="Created by" Index="24" BandIndex="0" RowIndex="0" ColIndex="24" Width="100"></COLUMN>
    <COLUMN Name="Created_Date" Caption="Created Date" Index="25" BandIndex="0" RowIndex="0" ColIndex="25" Width="100"></COLUMN>
    <COLUMN Name="CurrentDate" Caption="CurrentDate" Index="26" BandIndex="0" RowIndex="0" ColIndex="26" Width="100"></COLUMN>
    <COLUMN Name="CurrentTime" Caption="CurrentTime" Index="27" BandIndex="0" RowIndex="0" ColIndex="27" Width="100"></COLUMN>
    <COLUMN Name="Datasheet_Link" Caption="Datasheet Link" Index="28" BandIndex="0" RowIndex="0" ColIndex="28" Width="100"></COLUMN>
    <COLUMN Name="DatasheetVersion" Caption="DatasheetVersion" Index="29" BandIndex="0" RowIndex="0" ColIndex="29" Width="100"></COLUMN>
    <COLUMN Name="Date" Caption="Date" Index="30" BandIndex="0" RowIndex="0" ColIndex="30" Width="100"></COLUMN>
    <COLUMN Name="Description" Caption="Description" Index="31" BandIndex="0" RowIndex="0" ColIndex="31" Width="100"></COLUMN>
    <COLUMN Name="Designator" Caption="Designator" Index="32" BandIndex="0" RowIndex="0" ColIndex="32" Width="100"></COLUMN>
    <COLUMN Name="Designator_X_Mil_" Caption="Designator-X&#40;Mil&#41;" Index="33" BandIndex="0" RowIndex="0" ColIndex="33" Width="100"></COLUMN>
    <COLUMN Name="Designator_X_mm_" Caption="Designator-X&#40;mm&#41;" Index="34" BandIndex="0" RowIndex="0" ColIndex="34" Width="100"></COLUMN>
    <COLUMN Name="Designator_Y_Mil_" Caption="Designator-Y&#40;Mil&#41;" Index="35" BandIndex="0" RowIndex="0" ColIndex="35" Width="100"></COLUMN>
    <COLUMN Name="Designator_Y_mm_" Caption="Designator-Y&#40;mm&#41;" Index="36" BandIndex="0" RowIndex="0" ColIndex="36" Width="100"></COLUMN>
    <COLUMN Name="DesignItemId" Caption="DesignItemId" Index="37" BandIndex="0" RowIndex="0" ColIndex="37" Width="100"></COLUMN>
    <COLUMN Name="Direction" Caption="Direction" Index="38" BandIndex="0" RowIndex="0" ColIndex="38" Width="100"></COLUMN>
    <COLUMN Name="Document" Caption="Document" Index="39" BandIndex="0" RowIndex="0" ColIndex="39" Width="100"></COLUMN>
    <COLUMN Name="DocumentFullPathAndName" Caption="DocumentFullPathAndName" Index="40" BandIndex="0" RowIndex="0" ColIndex="40" Width="100"></COLUMN>
    <COLUMN Name="DocumentName" Caption="DocumentName" Index="41" BandIndex="0" RowIndex="0" ColIndex="41" Width="100"></COLUMN>
    <COLUMN Name="DocumentNumber" Caption="DocumentNumber" Index="42" BandIndex="0" RowIndex="0" ColIndex="42" Width="100"></COLUMN>
    <COLUMN Name="DrawnBy" Caption="DrawnBy" Index="43" BandIndex="0" RowIndex="0" ColIndex="43" Width="100"></COLUMN>
    <COLUMN Name="Engineer" Caption="Engineer" Index="44" BandIndex="0" RowIndex="0" ColIndex="44" Width="100"></COLUMN>
    <COLUMN Name="Footprint" Caption="Footprint" Index="45" BandIndex="0" RowIndex="0" ColIndex="45" Width="100"></COLUMN>
    <COLUMN Name="Height" Caption="Height" Index="46" BandIndex="0" RowIndex="0" ColIndex="46" Width="100"></COLUMN>
    <COLUMN Name="Height_Mil_" Caption="Height&#40;Mil&#41;" Index="47" BandIndex="0" RowIndex="0" ColIndex="47" Width="100"></COLUMN>
    <COLUMN Name="Height_mm_" Caption="Height&#40;mm&#41;" Index="48" BandIndex="0" RowIndex="0" ColIndex="48" Width="100"></COLUMN>
    <COLUMN Name="Ibis_Model" Caption="Ibis Model" Index="49" BandIndex="0" RowIndex="0" ColIndex="49" Width="100"></COLUMN>
    <COLUMN Name="ImagePath" Caption="ImagePath" Index="50" BandIndex="0" RowIndex="0" ColIndex="50" Width="100"></COLUMN>
    <COLUMN Name="Index" Caption="Index" Index="51" BandIndex="0" RowIndex="0" ColIndex="51" Width="100"></COLUMN>
    <COLUMN Name="Inductance" Caption="Inductance" Index="52" BandIndex="0" RowIndex="0" ColIndex="52" Width="100"></COLUMN>
    <COLUMN Name="IR_Max__uA_" Caption="IR Max &#40;uA&#41;" Index="53" BandIndex="0" RowIndex="0" ColIndex="53" Width="100"></COLUMN>
    <COLUMN Name="ItemGUID" Caption="ItemGUID" Index="54" BandIndex="0" RowIndex="0" ColIndex="54" Width="100"></COLUMN>
    <COLUMN Name="LatestRevisionDate" Caption="LatestRevisionDate" Index="55" BandIndex="0" RowIndex="0" ColIndex="55" Width="100"></COLUMN>
    <COLUMN Name="LatestRevisionNote" Caption="LatestRevisionNote" Index="56" BandIndex="0" RowIndex="0" ColIndex="56" Width="100"></COLUMN>
    <COLUMN Name="Length" Caption="Length" Index="57" BandIndex="0" RowIndex="0" ColIndex="57" Width="100"></COLUMN>
    <COLUMN Name="Library_Name" Caption="Library Name" Index="58" BandIndex="0" RowIndex="0" ColIndex="58" Width="100"></COLUMN>
    <COLUMN Name="Library_Reference" Caption="Library Reference" Index="59" BandIndex="0" RowIndex="0" ColIndex="59" Width="100"></COLUMN>
    <COLUMN Name="LibRef" Caption="LibRef" Index="60" BandIndex="0" RowIndex="0" ColIndex="60" Width="100"></COLUMN>
    <COLUMN Name="LogicalDesignator" Caption="LogicalDesignator" Index="61" BandIndex="0" RowIndex="0" ColIndex="61" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer" Caption="Manufacturer" Index="62" BandIndex="0" RowIndex="0" ColIndex="62" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_1" Caption="Manufacturer 1" Index="63" BandIndex="0" RowIndex="0" ColIndex="63" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_Part_Number" Caption="Manufacturer Part Number" Index="64" BandIndex="0" RowIndex="0" ColIndex="64" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_Part_Number_1" Caption="Manufacturer Part Number 1" Index="65" BandIndex="0" RowIndex="0" ColIndex="65" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_Name" Caption="Manufacturer_Name" Index="66" BandIndex="0" RowIndex="0" ColIndex="66" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_Part_Number1" Caption="Manufacturer_Part_Number" Index="67" BandIndex="0" RowIndex="0" ColIndex="67" Width="100"></COLUMN>
    <COLUMN Name="Maximum_Operating_Temperature" Caption="Maximum Operating Temperature" Index="68" BandIndex="0" RowIndex="0" ColIndex="68" Width="100"></COLUMN>
    <COLUMN Name="Minimum_Operating_Temperature" Caption="Minimum Operating Temperature" Index="69" BandIndex="0" RowIndex="0" ColIndex="69" Width="100"></COLUMN>
    <COLUMN Name="Minimum_Order_Quantity" Caption="Minimum Order Quantity" Index="70" BandIndex="0" RowIndex="0" ColIndex="70" Width="100"></COLUMN>
    <COLUMN Name="Model_Footprint" Caption="Model:Footprint" Index="71" BandIndex="0" RowIndex="0" ColIndex="71" Width="100"></COLUMN>
    <COLUMN Name="Model_Signal_Integrity" Caption="Model:Signal Integrity" Index="72" BandIndex="0" RowIndex="0" ColIndex="72" Width="100"></COLUMN>
    <COLUMN Name="Model_Simulation" Caption="Model:Simulation" Index="73" BandIndex="0" RowIndex="0" ColIndex="73" Width="100"></COLUMN>
    <COLUMN Name="Models" Caption="Models" Index="74" BandIndex="0" RowIndex="0" ColIndex="74" Width="100"></COLUMN>
    <COLUMN Name="ModifiedDate" Caption="ModifiedDate" Index="75" BandIndex="0" RowIndex="0" ColIndex="75" Width="100"></COLUMN>
    <COLUMN Name="Mounting_Style" Caption="Mounting Style" Index="76" BandIndex="0" RowIndex="0" ColIndex="76" Width="100"></COLUMN>
    <COLUMN Name="Mounting_Technology" Caption="Mounting Technology" Index="77" BandIndex="0" RowIndex="0" ColIndex="77" Width="100"></COLUMN>
    <COLUMN Name="Mouser_Part_Number" Caption="Mouser Part Number" Index="78" BandIndex="0" RowIndex="0" ColIndex="78" Width="100"></COLUMN>
    <COLUMN Name="Mouser_Price_Stock" Caption="Mouser Price/Stock" Index="79" BandIndex="0" RowIndex="0" ColIndex="79" Width="100"></COLUMN>
    <COLUMN Name="NoPins" Caption="NoPins" Index="80" BandIndex="0" RowIndex="0" ColIndex="80" Width="100"></COLUMN>
    <COLUMN Name="Operating_Supply_Current" Caption="Operating Supply Current" Index="81" BandIndex="0" RowIndex="0" ColIndex="81" Width="100"></COLUMN>
    <COLUMN Name="Operating_Temperature_Range" Caption="Operating Temperature Range" Index="82" BandIndex="0" RowIndex="0" ColIndex="82" Width="100"></COLUMN>
    <COLUMN Name="Organization" Caption="Organization" Index="83" BandIndex="0" RowIndex="0" ColIndex="83" Width="100"></COLUMN>
    <COLUMN Name="Package___Case" Caption="Package / Case" Index="84" BandIndex="0" RowIndex="0" ColIndex="84" Width="100"></COLUMN>
    <COLUMN Name="PackageDescription" Caption="PackageDescription" Index="85" BandIndex="0" RowIndex="0" ColIndex="85" Width="100"></COLUMN>
    <COLUMN Name="PackageReference" Caption="PackageReference" Index="86" BandIndex="0" RowIndex="0" ColIndex="86" Width="100"></COLUMN>
    <COLUMN Name="PackageVersion" Caption="PackageVersion" Index="87" BandIndex="0" RowIndex="0" ColIndex="87" Width="100"></COLUMN>
    <COLUMN Name="Packaging" Caption="Packaging" Index="88" BandIndex="0" RowIndex="0" ColIndex="88" Width="100"></COLUMN>
    <COLUMN Name="Packing" Caption="Packing" Index="89" BandIndex="0" RowIndex="0" ColIndex="89" Width="100"></COLUMN>
    <COLUMN Name="partNo" Caption="partNo" Index="90" BandIndex="0" RowIndex="0" ColIndex="90" Width="100"></COLUMN>
    <COLUMN Name="PartNumber" Caption="PartNumber" Index="91" BandIndex="0" RowIndex="0" ColIndex="91" Width="100"></COLUMN>
    <COLUMN Name="PartType" Caption="PartType" Index="92" BandIndex="0" RowIndex="0" ColIndex="92" Width="100"></COLUMN>
    <COLUMN Name="PCB3D" Caption="PCB3D" Index="93" BandIndex="0" RowIndex="0" ColIndex="93" Width="100"></COLUMN>
    <COLUMN Name="PhysicalPath" Caption="PhysicalPath" Index="94" BandIndex="0" RowIndex="0" ColIndex="94" Width="100"></COLUMN>
    <COLUMN Name="Pins" Caption="Pins" Index="95" BandIndex="0" RowIndex="0" ColIndex="95" Width="100"></COLUMN>
    <COLUMN Name="PPK_Max__W_" Caption="PPK Max &#40;W&#41;" Index="96" BandIndex="0" RowIndex="0" ColIndex="96" Width="100"></COLUMN>
    <COLUMN Name="Pricing_1" Caption="Pricing 1" Index="97" BandIndex="0" RowIndex="0" ColIndex="97" Width="100"></COLUMN>
    <COLUMN Name="Product_Type" Caption="Product Type" Index="98" BandIndex="0" RowIndex="0" ColIndex="98" Width="100"></COLUMN>
    <COLUMN Name="Project" Caption="Project" Index="99" BandIndex="0" RowIndex="0" ColIndex="99" Width="100"></COLUMN>
    <COLUMN Name="ProjectName" Caption="ProjectName" Index="100" BandIndex="0" RowIndex="0" ColIndex="100" Width="100"></COLUMN>
    <COLUMN Name="Published" Caption="Published" Index="101" BandIndex="0" RowIndex="0" ColIndex="101" Width="100"></COLUMN>
    <COLUMN Name="Publisher" Caption="Publisher" Index="102" BandIndex="0" RowIndex="0" ColIndex="102" Width="100"></COLUMN>
    <COLUMN Name="Quantity" Caption="Quantity" Index="103" BandIndex="0" RowIndex="0" ColIndex="103" Width="100"></COLUMN>
    <COLUMN Name="Reeling" Caption="Reeling" Index="104" BandIndex="0" RowIndex="0" ColIndex="104" Width="100"></COLUMN>
    <COLUMN Name="Revision" Caption="Revision" Index="105" BandIndex="0" RowIndex="0" ColIndex="105" Width="100"></COLUMN>
    <COLUMN Name="RevisionGUID" Caption="RevisionGUID" Index="106" BandIndex="0" RowIndex="0" ColIndex="106" Width="100"></COLUMN>
    <COLUMN Name="RoHS" Caption="RoHS" Index="107" BandIndex="0" RowIndex="0" ColIndex="107" Width="100"></COLUMN>
    <COLUMN Name="RoHS___Mouser" Caption="RoHS - Mouser" Index="108" BandIndex="0" RowIndex="0" ColIndex="108" Width="100"></COLUMN>
    <COLUMN Name="RS_Part_Number" Caption="RS Part Number" Index="109" BandIndex="0" RowIndex="0" ColIndex="109" Width="100"></COLUMN>
    <COLUMN Name="RS_Price_Stock" Caption="RS Price/Stock" Index="110" BandIndex="0" RowIndex="0" ColIndex="110" Width="100"></COLUMN>
    <COLUMN Name="Rule" Caption="Rule" Index="111" BandIndex="0" RowIndex="0" ColIndex="111" Width="100"></COLUMN>
    <COLUMN Name="Series" Caption="Series" Index="112" BandIndex="0" RowIndex="0" ColIndex="112" Width="100"></COLUMN>
    <COLUMN Name="SheetNumber" Caption="SheetNumber" Index="113" BandIndex="0" RowIndex="0" ColIndex="113" Width="100"></COLUMN>
    <COLUMN Name="SheetTotal" Caption="SheetTotal" Index="114" BandIndex="0" RowIndex="0" ColIndex="114" Width="100"></COLUMN>
    <COLUMN Name="Signal_Integrity" Caption="Signal Integrity" Index="115" BandIndex="0" RowIndex="0" ColIndex="115" Width="100"></COLUMN>
    <COLUMN Name="Simulation" Caption="Simulation" Index="116" BandIndex="0" RowIndex="0" ColIndex="116" Width="100"></COLUMN>
    <COLUMN Name="size" Caption="size" Index="117" BandIndex="0" RowIndex="0" ColIndex="117" Width="100"></COLUMN>
    <COLUMN Name="SourceLibraryName" Caption="SourceLibraryName" Index="118" BandIndex="0" RowIndex="0" ColIndex="118" Width="100"></COLUMN>
    <COLUMN Name="Standard_Pack_Qty" Caption="Standard Pack Qty" Index="119" BandIndex="0" RowIndex="0" ColIndex="119" Width="100"></COLUMN>
    <COLUMN Name="Stock_1" Caption="Stock 1" Index="120" BandIndex="0" RowIndex="0" ColIndex="120" Width="100"></COLUMN>
    <COLUMN Name="Subcategory" Caption="Subcategory" Index="121" BandIndex="0" RowIndex="0" ColIndex="121" Width="100"></COLUMN>
    <COLUMN Name="Sub_Parts" Caption="Sub-Parts" Index="122" BandIndex="0" RowIndex="0" ColIndex="122" Width="100"></COLUMN>
    <COLUMN Name="Supplier_1" Caption="Supplier 1" Index="123" BandIndex="0" RowIndex="0" ColIndex="123" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Currency_1" Caption="Supplier Currency 1" Index="124" BandIndex="0" RowIndex="0" ColIndex="124" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Order_Qty_1" Caption="Supplier Order Qty 1" Index="125" BandIndex="0" RowIndex="0" ColIndex="125" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Part_Number_1" Caption="Supplier Part Number 1" Index="126" BandIndex="0" RowIndex="0" ColIndex="126" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Stock_1" Caption="Supplier Stock 1" Index="127" BandIndex="0" RowIndex="0" ColIndex="127" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Subtotal_1" Caption="Supplier Subtotal 1" Index="128" BandIndex="0" RowIndex="0" ColIndex="128" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Unit_Price_1" Caption="Supplier Unit Price 1" Index="129" BandIndex="0" RowIndex="0" ColIndex="129" Width="100"></COLUMN>
    <COLUMN Name="Time" Caption="Time" Index="130" BandIndex="0" RowIndex="0" ColIndex="130" Width="100"></COLUMN>
    <COLUMN Name="Title" Caption="Title" Index="131" BandIndex="0" RowIndex="0" ColIndex="131" Width="100"></COLUMN>
    <COLUMN Name="typr" Caption="typr" Index="132" BandIndex="0" RowIndex="0" ColIndex="132" Width="100"></COLUMN>
    <COLUMN Name="UniqueIdName" Caption="UniqueIdName" Index="133" BandIndex="0" RowIndex="0" ColIndex="133" Width="100"></COLUMN>
    <COLUMN Name="UniqueIdPath" Caption="UniqueIdPath" Index="134" BandIndex="0" RowIndex="0" ColIndex="134" Width="100"></COLUMN>
    <COLUMN Name="V_BR__Typ__V_" Caption="V&#40;BR&#41; Typ &#40;V&#41;" Index="135" BandIndex="0" RowIndex="0" ColIndex="135" Width="100"></COLUMN>
    <COLUMN Name="Value" Caption="Value" Index="136" BandIndex="0" RowIndex="0" ColIndex="136" Width="100"></COLUMN>
    <COLUMN Name="Variant" Caption="Variant" Index="137" BandIndex="0" RowIndex="0" ColIndex="137" Width="100"></COLUMN>
    <COLUMN Name="VaultGUID" Caption="VaultGUID" Index="138" BandIndex="0" RowIndex="0" ColIndex="138" Width="100"></COLUMN>
    <COLUMN Name="Width" Caption="Width" Index="139" BandIndex="0" RowIndex="0" ColIndex="139" Width="100"></COLUMN>
    <COLUMN Name="_" Caption="&#35;" Index="140" BandIndex="0" RowIndex="0" ColIndex="140" Width="100"></COLUMN>
    <COLUMN Name="_ID_" Caption="&#37;ID&#37;" Index="141" BandIndex="0" RowIndex="0" ColIndex="141" Width="100"></COLUMN>
    <COLUMN Name="_PARENTID_" Caption="&#37;PARENTID&#37;" Index="142" BandIndex="0" RowIndex="0" ColIndex="142" Width="100"></COLUMN>
  </COLUMNS>
  <ROWS>
    <ROW Address1="" Address2="" Address3="" Address4="" Application_BuildNumber="" ApprovedBy="" Author="" Brand="" Category="" CheckedBy="" Class="" Code___JEDEC="" Comment="mSMD300" CompanyName="" Component_Kind="Standard" ComponentKind="0" ComponentLink1_Description="" ComponentLink1Description="" ComponentLink1URL="" ComponentLink2_Description="" ComponentLink2Description="" ComponentLink2URL="" ComponentLink3Description="" ComponentLink3URL="" Created_by="" Created_Date="" CurrentDate="1/5/19" CurrentTime="10:24:10 AM" Datasheet_Link="" DatasheetVersion="" Date="" Description="" Designator="" Designator_X_Mil_="2508.269" Designator_X_mm_="63.71" Designator_Y_Mil_="8172.761" Designator_Y_mm_="207.588" DesignItemId="mSMD300" Direction="" Document="C:&#92;Users&#92;Public&#92;Documents&#92;Altium&#92;Projects&#92;AIO_3399J_Schematic&#92;DC_IN.SchDoc" DocumentFullPathAndName="C:&#92;Users&#92;Public&#92;Documents&#92;Altium&#92;Projects&#92;AIO_3399J_Schematic&#92;DC_IN.SchDoc" DocumentName="DC_IN.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="" Height="" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="1" Inductance="" IR_Max__uA_="" ItemGUID="" LatestRevisionDate="" LatestRevisionNote="" Length="" Library_Name="Schlib2.SchLib" Library_Reference="mSMD300" LibRef="mSMD300" LogicalDesignator="" Manufacturer="" Manufacturer_1="" Manufacturer_Part_Number="" Manufacturer_Part_Number_1="" Manufacturer_Name="" Manufacturer_Part_Number1="" Maximum_Operating_Temperature="" Minimum_Operating_Temperature="" Minimum_Order_Quantity="" Model_Footprint="" Model_Signal_Integrity="" Model_Simulation="" Models="0" ModifiedDate="1/5/19" Mounting_Style="" Mounting_Technology="" Mouser_Part_Number="" Mouser_Price_Stock="" NoPins="" Operating_Supply_Current="" Operating_Temperature_Range="" Organization="" Package___Case="" PackageDescription="" PackageReference="" PackageVersion="" Packaging="" Packing="" partNo="" PartNumber="" PartType="mSMD300" PCB3D="" PhysicalPath="DC_IN" Pins="2" PPK_Max__W_="" Pricing_1="" Product_Type="" Project="C:&#92;Users&#92;Public&#92;Documents&#92;Altium&#92;Projects&#92;AIO_3399J_Schematic&#92;AIO_3399J_Schematic.PrjPcb" ProjectName="AIO_3399J_Schematic.PrjPcb" Published="" Publisher="" Quantity="1" Reeling="" Revision="" RevisionGUID="" RoHS="" RoHS___Mouser="" RS_Part_Number="" RS_Price_Stock="" Rule="" Series="" SheetNumber="" SheetTotal="5" Signal_Integrity="" Simulation="" size="" SourceLibraryName="Schlib2.SchLib" Standard_Pack_Qty="" Stock_1="" Subcategory="" Sub_Parts="1" Supplier_1="" Supplier_Currency_1="" Supplier_Order_Qty_1="" Supplier_Part_Number_1="" Supplier_Stock_1="" Supplier_Subtotal_1="" Supplier_Unit_Price_1="" Time="" Title="" typr="" UniqueIdName="LTNHJKPI" UniqueIdPath="" V_BR__Typ__V_="" Value="" Variant="" VaultGUID="" Width="" _="1" _ID_="1613711072" _PARENTID_=""></ROW>